//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanillaAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VanillaAnalyzer.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一一
        ///一丁不視
        ///一丁不视
        ///一万
        ///一下
        ///一下子
        ///一不做二不休
        ///一专多能
        ///一世
        ///一世之雄
        ///一世紀
        ///一世纪
        ///一丘一壑
        ///一丘之貉
        ///一丛
        ///一丝
        ///一丝一毫
        ///一丝不挂
        ///一丝不线单木不林
        ///一丝不苟
        ///一两句话
        ///一並
        ///一並處理
        ///一个
        ///一个中心
        ///一个劲儿
        ///一个又一个
        ///一个国家两种制度
        ///一个样
        ///一中全会
        ///一中全會
        ///一串
        ///一举
        ///一举一动
        ///一举两便
        ///一举两得
        ///一举千里
        ///一举多得
        ///一举成名
        ///一举手之劳
        ///一之为甚
        ///一之已甚
        ///一之為甚
        ///一之謂甚
        ///一之谓甚
        ///一九
        ///一九九一
        ///一九九七
        ///一九九二
        ///一九九六
        ///一九九Ｏ
        ///一九八七
        ///一九八八
        ///一书
        ///一了千明
        ///一了百了
        ///一了百当
        ///一了百當
        ///一事
        ///一事无成
        ///一事無成
        ///一二
        ///一二十年
        ///一五一十
        ///一些
        ///一些人
        ///一些单位
        ///一些單位
        ///一亮
        ///一人
        ///一人之下
        ///一人之交
        ///一人传虚万人传实
        ///一人做事一人当
        ///一人做事一人當
        ///一人傳虛萬人傳實
        ///一人得道雞犬升天
        ///一人得道鸡犬升天
        ///一亿
        ///一介
        ///一介不取
        ///一仍旧贯
        ///一仍舊貫
        ///一代
        ///一代人
        ///一代宗臣
        ///一代新人
        ///一代 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dict {
            get {
                return ResourceManager.GetString("Dict", resourceCulture);
            }
        }
    }
}
